### ISSUE TITLE
Mod textures

### ISSUE THREAD

**Issue by SimonMeskens** [DashieDev/DoggyTalentsNext#1]
Hey, I'm ZhilBear, texture artist for the old mod.

I did the dog textures for RaustBlackDragon way back and I was wondering if these are still being used in this new port. If so, could I get artist's credits on Curseforge? I've always been rather proud of those textures and I love to see the project receive a new life :)

You should be able to verify in the credits of the old mod that I'm the artist (ZhilBear)

**Comment by DashieDev** [comment]
Oh! I am super sorry I didn't credit you! 😭Please forgive me! I actually was going to include you but haven't gotten the chance since I was so busy with the internal logic of the mod (and also another project) Thanks for reminding me. It is good that you are still active, and I would like to say, your work is EXCELLENT!  I love your texture design, especially the texture for the doggy suit, which I promoted a lot on the page ❤️ It is like your dog being a pianist! Once again I am so sorry, I am actually trying my best to credit everyone who contributed :)  and i am so sorry that I didn't reply instantly because I just got home after rehearsing in a piano concert, and it was stressful as hell :)) 
update: Done! I credited you with a 35% CF split, although I don't know what that means :))) 
ps : do you have any idea where RaustBlackDragon is now ?........

**Comment by SimonMeskens** [comment]
I haven't seen Raust in a good long while unfortunately, would love to catch up with them, it's been too long. Thanks for the credits :)

I didn't make all the textures btw (I don't know from memory which I made, I think I did most of the different dog breeds and most of the items, but I don't know beyond that). The previous author should have a list they received from Raust with proper credits, you should try asking if they can provide a similar list for you.

**Comment by DashieDev** [comment]
ProPercivalab is the previous author to be exact. And i can't seems to be able to contact him for months now ..... Like i have send him  a lot of message, and all of them are pretty long, describing my intention......I even PM him on CurseForge...... Like i haven't seen his presence on the internet since he sent me a final letter, which is here https://github.com/percivalalb/DoggyTalents/pull/402#issuecomment-1152874076
And also that i don't really know if DoggyTalentsNext is even allowed tbh ..... i spent a lot of heart and soul on the mod (beside updating the mod i made a lot of changes which improves it in general.... , and i catches a lot of bug in the old mod too, you can see on the changelog)  By any chances, do you have any ways to contact him ?

**Comment by SimonMeskens** [comment]
I don't. My interactions with him were always amicable though, so I'm sure he'll give you the proper greenlight if he ever returns :)

You're doing a good thing here, don't worry, I'm sure everything will work out :)

**Comment by DashieDev** [comment]
Thanks A lot Mr.Simon, i just matriculated into university recently, still got a lot to learn 😅 Working on the mod helps me a lot in my coding/ project developing skill in general , and i love dogs and minecraft wolves/dogs too. The mod is like, my emotional children now. Your reassurance means a lot to me ❤️
