### ISSUE TITLE
Compatibility Crash with Domestication Innovation

### ISSUE THREAD

**Issue by finesseseth** [DashieDev/DoggyTalentsNext#107]
We are hosting a Life in the Village 3 server and have discovered a crash that appears to be an interaction between Doggy Talents Next and Domestication Innovation. When a tamed dog from DTN is given a Collar from DI that has the Tethered Teleport enchant, teleporting from other dimensions to the overworld crashes the server, I can also reproduce this in singleplayer.

DI hasn't seen an update in a while so I'm hoping this is the right place as the Collar works fine on vanilla dogs and other animals. In the mean time DTN has it's own way of teleporting with the owner but it's hard to enforce that on a public server. Banning the Collar wouldn't be a good solution.

Server Crashlog: https://mclo.gs/FpPxJxg

Latest LitV 3
Minecraft 1.19.2
DI 1.6.1
DTN 1.18.11

For good measure also tested on a fresh empty forge install of just the latest versions DI and DTN in minecraft 1.20.1 and could still reproduce it in singleplayer -> https://mclo.gs/jFEpcKh

Happy to provide anything else you need.

**Comment by DashieDev** [comment]
This is currently expected behaviour when using that specific feature on DI on DTN dogs and is out of our control as the issue is on DI side and i have predicted and confirmed it a while ago. Please avoid using DI features on DTN Dogs and if possible blacklist DTN Dogs from using DI's collar as they seem to have provided that ability on their side. For more information, see
https://doggytalentsnext.wiki.gg/wiki/FAQ#About_Compatibility_with_Domestication_Innovation_and_similar_Tamable_improvement_mods%2E

**Comment by finesseseth** [comment]
Thank you for the info.

I'm looking where I can take the recommended action "The player can configure DI to exclude DTN Dogs if possible to avoid conflict."

The wording on that "if possible" does that mean the option exists in DI or not, can't find it in the configs so far.

**Comment by DashieDev** [comment]
https://github.com/AlexModGuy/DomesticationInnovation/issues/101 this seems interesting.
I would recommend consulting their team or their discord for advice since i don't have control on DI unfortunately.
