### ISSUE TITLE
Dog revive command doesn't work

### ISSUE THREAD

**Issue by NovaViper** [DashieDev/DoggyTalentsNext#118]
I try to run `/dog revive byname NovaViper "DoggyName"` but it just says `No Dogs under the identifier "DoggyName" were found` every time I try to run it. Also I notice the console doesn't try to autocomplete it, almost like the command doesn't exist at all. It only lets me autocomplete up until `/dog revive byname/byuuid`, but after that, nothing else automcompletes. Verses when I try for `/dog locate`, it autocompletes everything including the dog's name and its owner's name. There isn't anything in the logs that would help troubleshoot either.

Minecraft Version: 1.20.1
Forge Version: 47.3.12
Doggy Talents version: 1.18.39

**Comment by DashieDev** [comment]
Could you provide us with more infornation of the situation? Like what your dog name is and is it got killed (not incapacitated/injured).

**Comment by NovaViper** [comment]
The dog is incapacitated and I'm trying to revive them quickly with the command. The dog's name is Maxxie

**Comment by DashieDev** [comment]
To revive an Incapacitated Dog, right click it with a Totem Of Undying. The command/bed revival method doesnt work because the dog is not techically dead and is in fact still alive in your world, therefore it is not available in the respawn storage. 
For more information, see [Immortal Dogs](https://doggytalentsnext.wiki.gg/wiki/Immortal_Dogs)

**Comment by NovaViper** [comment]
Ah that explains it! I didn't realize the revive command only worked on dogs that actually died. Will close and thanks!
