### ISSUE TITLE
Game froze, force stopped it, dog was erased after loading up

### ISSUE THREAD

**Issue by CrazyPenguin22** [DashieDev/DoggyTalentsNext#2]
Description: I was running at night with my dog who was behind me placing torches automatically (level 5), and suddenly I was the only one who could move and nothing else, the entire game froze, as well as my dog (next to him newly placed torch). I force closed the game, and when I loaded back the game and my world, I was placed couple of minutes (5-10min) in past with my dog completely gone. I went to the place where my game froze, and there was no dog there either. I completely lost him.

I am using this mod in my Better MC+ modpack for 1.19.2 as well as couple of added mods as well. Biomes are Biomes o plenty and Terralift. So I don't know what biome or block this happened on because there is too much of new ones.

Crash log:
[https://gist.github.com/CrazyPenguin22/673521975f7251144803c275f767b333](url)

**Comment by DashieDev** [comment]
Thanks for posting on github ❤️ But this is kinda wierd because in the log file stack trace it doesn't involves the mod........ as you can see....... And judging by the..... relatively..... huge ..... amount you installed..... i am not sure if that is even because DoggyTalents..... Because on my side i have experienced with a lot of wierd stuff like that before... like .... I was in a server running on my pc and for some reason (I think that was OBS) cause the whole system to freeze and then crashes minecraft for some reasons, and i joined back in and all three of my dog ..... i mean..... VANILLA dog ..... is ..... gone :(( It was kinda hard for me to debug this now. Still i will try my best to take a look, and notify you when there is update. Also by any chance, Do you have any screenshots or video recordings? If so could u pls provide it?Because it will help a lot in debugging.... Meanwhile you could try yo replicate the bug, i am currently trying to replicate it on my end too via rigurously testing my TorchDog

**Comment by CrazyPenguin22** [comment]
Maybe its a wrong log file sorry, the game froze and I force closed it (did not create a crash report). And I posted the latest one I found in my crash log folder, since I did not have any crashes later.

Reason why I think this mod was causing it because:
- I just leveled up dog to lvl 5 torch talent, went about 200-300 blocks away and the crash happened
- When I turned around to see if my dog is moving when I notice the game froze, I saw him standing still right next to the newly placed torch
- The game removed the dog after I logged back in (might be because it caused the issue)
- I went to the same spot again without the dog this time, crash did not happen
- I did not experience any heavy freezes like this until I installed this mod


But it also might be something else, its really hard to tell with all these mods. The reason I mentioned above is why I though it was this mod causing it

I don't have a screenshot but I can backup my world and do some testing to get another torch dog and move around see if the game freezes again

**Comment by DashieDev** [comment]
It would be nice if you can do some testing for the TorchDog feature alongside with the other mods, as it would have a higher chance of replicating the bug. In my experience with the mod before, in 1.16.5 there is some pretty wierd stuff too, like, it froze like that and it make me wait for a momment and then when it got back to normal like ..... my dog suddenly became......... fireproof ?? ........But stuff like that is pretty rare to be honest, and can happen any time .....

**Comment by pietro0games** [comment]
Just a little update on this:
This bug can happen with any type of crash, this mod doesn't cause crashes. It seems a vanilla bug due to old reports I was able to find, related to following pets. For some reason, even the game doesn't consider the dog as a real entity anymore, The Radar keeps tracking the last point of the dogs, showing the names and beds keep linked to them. I lost many dogs due to this bug, Im still trying to find a way to get back them due the Radar keeping tracking many more.
Note:Yeah, I tested the commands from this mod, but it doesn't recognize the name of the dogs

**Comment by DashieDev** [comment]
Yeah.... There is a point when i was playing with my brother and although that world have the OG DoggyTalents, no dogs have been trained up to that point so the mod have completely no effects. It was a LAN World opened from my Singleplayer instance. I tamed 3 vanilla wolves/dogs. We were just about to go home but suddenly the whole instance crash without throwing anything, and what weird is that my recording software OBS also crashes alongside that, everything else on my pc was normal. But then I re-join and boom, all 3 of the dogs is gone. But do note that most crashes i see (ex: NullPointerException, ClassCastException......)  aren't that serious to violate data integrity because Minecraft caught that and save everything before shutting down, but also do note that if there is something wrong when an entity is read from disk, if the mod didn't catch and Minecraft caught it, it will end up discarding the entity completely, also i have known some crashes that will result in corruption (StackOverflowException)
