### ISSUE TITLE
Dog Armor color of armor does not match armor that was used

### ISSUE THREAD

**Issue by PiDay314** [DashieDev/DoggyTalentsNext#39]
Hello! Love this mod and appreciate all the work that goes into it.

When putting armor on my dog via the Guard Dog talent (if I remember right), I noticed the armor defaults to look like Iron armor regardless of the armor actually used.  Would it be possible to have it correctly display the color of the armor?  

If possible, could this include new armor from mods as well?

Armor tried: Leather (Vanilla/Not Dyed), Obsidian (Mo'Shizz)
Skins:  Default (Vanilla), skin #71 from the texture pack (white wolf with blue eyes)
Armor color result:  Iron
Minecraft Version:  1.20.01
Doggy Talent Version:  1.16.3

**Comment by DashieDev** [comment]
Sorry for the late reply! Unfortunately, this behaviour is expected for now as every armor has to have a dedicated equivalent texture design for DTN in other for it to render as DTN cannot reuse the humanoid texture, which is why it defaulted to the Iron Texture. However, in the future we might allow support for third party armor in the form of resourcepacks.
