### ISSUE TITLE
not an issue per sea but a question

### ISSUE THREAD

**Issue by CharCharthemonkey** [DashieDev/DoggyTalentsNext#8]
is it possible to get a config to re enable adding the coin on startup pretty pls?

**Comment by DashieDev** [comment]
The config is still there actually. 
Go to ```<your server's world file>/serverconfig/doggytalents-server.toml```
There will be an entry called ```enable_starting_items```,  set it to true, now every other player that first joined that world will have the Doggy Charm, which I think is what you meant. 
Although i will be moving that into the common config file to allow for pre-world-create enabling.

**Comment by CharCharthemonkey** [comment]
to clarify i meant in the original mod (doggy talents) there was a "give starter coin on world join" i was hoping for that just so instead of trying to find enough bones to get a wolf then turn it to a DTN doggo one would just have the coin and get one that way

**Comment by CharCharthemonkey** [comment]
#When enabled you will spawn with a guide, Doggy Charm and Command Emblem.
	enable_starting_items = false
	
	this but per world instead of just having to go into the "server" configs to find it

**Comment by DashieDev** [comment]
Hmm.... the thing is, that particular part i haven't did anything much in my version, i just looked at the original source code and there is no option to config it globally. I think they removed it since DoggyTalents 2 started. But don't worry i will add it back.
And btw i think you can enable it after you join any world in that world's folder, which i said ```<your server world folder``` but it could be a singleplayer world and then log back in, you will have the item .

**Comment by CharCharthemonkey** [comment]
i will try that ty tho id wanna be able to get the coin on world load not have to load a world log out change a config then reload just to get if possible pls

**Comment by MatchaTeaBish** [comment]
Does this mod work with doggytalents 2 or should it be deleted before?
